import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { getBaseUrl } from "@/lib/utils/base-url";
import { AppProvider } from "@/lib/context/AppContext";
import Toast from "@/components/atoms/Toast/Toast";
import RuntimeEnvScript from "@/components/atoms/RuntimeEnvScript/RuntimeEnvScript";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(getBaseUrl()),
  title: "Next App Template",
  description: "Generated by create next app",
  openGraph: {
    title: "Next App Template",
    description: "Generated by create next app",
  },
  twitter: {
    card: "summary_large_image",
    title: "Next App Template",
    description: "Generated by create next app",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang={locale}>
      <head>
        <RuntimeEnvScript nonce={nonce} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <AppProvider>
            {children}
            <Toast />
          </AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
